# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginValidation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginValidation
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'MaterialComponents/Buttons'

end
