# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Study
  pod 'RxSwift'
  pod 'RxCocoa'
end
